services:
  postgres:
    image: postgres:16-alpine
    container_name: app-infrastructure_postgres
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      POSTGRES_DB: app-infrastructure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge